name: Metrics
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
  push:
    branches: ['main']

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_GH_TOKEN }}

          base_indepth: true
          base_hireable: true
          optimize: css,xml
          # experimental_features: --optimize-svg
          # config_output: markdown
          markdown_cache: .cache

          # Introduction (https://github.com/lowlighter/metrics/tree/master/source/plugins/introduction)
          plugin_introduction: yes
          # IsometricCalendar (https://github.com/lowlighter/metrics/tree/master/source/plugins/isocalendar)
          plugin_isocalendar: true

          #PageSpeed (https://github.com/lowlighter/metrics/tree/master/source/plugins/pagespeed)
          plugin_pagespeed: true
          plugin_pagespeed_url: https://www.phyrone.de/
          plugin_pagespeed_detailed: true
          plugin_pagespeed_pwa: false
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_API_KEY}}

          # Habits (https://github.com/lowlighter/metrics/tree/master/source/plugins/habits)
          plugin_habits: true
          plugin_habits_facts: true
          plugin_habits_charts: true
          config_timezone: Europe/Berlin

          # Lines (https://github.com/lowlighter/metrics/tree/master/source/plugins/lines)
          plugin_lines: true

          # Languages (https://github.com/lowlighter/metrics/tree/master/source/plugins/languages)
          plugin_languages: true
          plugin_languages_indepth: true
          plugin_languages_sections: most-used,recently-used
          plugin_languages_ignored: yacc

          # AniList (https://github.com/lowlighter/metrics/tree/master/source/plugins/anilist)
          plugin_anilist: true
          plugin_anilist_user: phyrone

          # Music (https://github.com/lowlighter/metrics/tree/master/source/plugins/music)
          #plugin_music: true
          #plugin_music_provider: spotify
          #plugin_music_user: nemo.mus

          # Achievements (https://github.com/lowlighter/metrics/tree/master/source/plugins/achievements)
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: true
